VIA_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
CONSOLE_ENABLE = no     # Console for debug(+400)
AUDIO_ENABLE   = no     # Audio output on port C6
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE  = no
LTO_ENABLE = yes
RGB_MATRIX_SUPPORTED = no
RGBLIGHT_SUPPORTED = no

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
